FROM python:3.10-slim

WORKDIR /mlflow

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git curl && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow

EXPOSE 5000

CMD mlflow server \
    --backend-store-uri sqlite:///mlflow_data/mlflow.db \
    --default-artifact-root /mlflow/mlflow_data/mlruns \
    --host 0.0.0.0 \
    --port 5000 \
    --serve-artifacts
