services:  
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow/mlflow_data
    networks:
      - ml-network

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    # disable all authentications: don't use to expose ports on public internet!
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root 
      --ServerApp.token='' 
      --ServerApp.password='' 
      --ServerApp.disable_check_xsrf=True
    networks:
      - ml-network
    depends_on:
      - mlflow

networks:
  ml-network:
    driver: bridge
