# Auto-generated Bboxes - Mapillary Tools
# Do not edit this file manually

BOUNDING_BOXES = {
    "57": {
        "ll_lat": 45.788961,
        "ll_lon": 6.614778,
        "ur_lat": 47.092146,
        "ur_lon": 8.114778,
        "nome": 57,
    }
}

# Total: 31
