import os
from dotenv import load_dotenv

load_dotenv()

initial_bbox = tuple(map(float, os.getenv("INITIAL_BBOX").split(',')))
bboxes_to_remove = list(map(int, os.getenv("BBOXES_TO_REMOVE").split(',')))
lat_step = float(os.getenv("LAT_STEP_BBOX"))
lon_step = float(os.getenv("LON_STEP_BBOX"))

current_directory = os.path.dirname(os.path.abspath(__file__))
output_filename = os.path.join(current_directory, "bounding_boxes.py")

def genera_grid():
    min_lat, min_lon, max_lat, max_lon = initial_bbox

    # Genera margini delle coordinate
    lat_edges = []
    current_lat = min_lat
    while current_lat < max_lat:
        lat_edges.append(current_lat)
        current_lat += lat_step
    lat_edges.append(max_lat)

    lon_edges = []
    current_lon = min_lon
    while current_lon < max_lon:
        lon_edges.append(current_lon)
        current_lon += lon_step
    lon_edges.append(max_lon)

    bounding_boxes = {}
    bbox_id = 1

    # Genera tutte le bbox
    for i in range(len(lat_edges)-1):
        for j in range(len(lon_edges)-1):
            bbox = (
                lat_edges[i],    # ll_lat
                lon_edges[j],    # ll_lon
                lat_edges[i+1],  # ur_lat
                lon_edges[j+1]   # ur_lon
            )
            current_id = str(bbox_id)  # ID come stringa
            
            if bbox_id in bboxes_to_remove:
                bbox_id += 1
                continue

            # Aggiungi al dizionario
            bounding_boxes[current_id] = {
                "ll_lat": bbox[0],
                "ll_lon": bbox[1],
                "ur_lat": bbox[2],
                "ur_lon": bbox[3],
                "nome": current_id
            }

            bbox_id += 1

    with open(output_filename, 'w') as f:
        f.write("# Auto-generated Bboxes - Mapillary Tools\n")
        f.write("# Do not edit this file manually\n\n")
        f.write("BOUNDING_BOXES = {\n")
        for bid, values in bounding_boxes.items():
            f.write(f'    "{bid}": {{\n')
            f.write(f'        "ll_lat": {values["ll_lat"]:.6f},\n')
            f.write(f'        "ll_lon": {values["ll_lon"]:.6f},\n')
            f.write(f'        "ur_lat": {values["ur_lat"]:.6f},\n')
            f.write(f'        "ur_lon": {values["ur_lon"]:.6f},\n')
            f.write(f'        "nome": {values["nome"]},\n')
            f.write('    },\n')
        f.write("}\n")
        f.write(f"\n# Total: {len(bounding_boxes)}\n")

if __name__ == "__main__":
    genera_grid()
    print(f"File Python generato: {output_filename}")